added JWT support
c-kalenyk/book-store pull request #12
Opened 2024-08-30 11:00 UTC by c-kalenyk

2024-08-30 12:39 UTC, okuzan requested changes

2024-08-30 12:39 UTC, okuzan commented on src/main/java/mate/academy/bookstore/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
Create a constant for bearer, instead of 7 use its .length()

2024-08-30 12:39 UTC, okuzan commented on src/main/java/mate/academy/bookstore/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader("Authorization");
check if you have a constant for this too, like import static jakarta.ws.rs.core.HttpHeaders.AUTHORIZATION

2024-08-31 17:23 UTC, sarakhmen approved these changes

2024-08-31 18:19 UTC, merged