added shopping cart entity
c-kalenyk/book-store pull request #14
Opened 2024-08-31 16:23 UTC by c-kalenyk

Same problem with insertion by liquibase like in previous PR

2024-09-02 09:30 UTC, okuzan approved these changes

2024-09-02 09:30 UTC, okuzan commented on src/main/java/mate/academy/bookstore/controller/ShoppingCartController.java
> +    public CartItemDto updateCartItemQuantity(@PathVariable Long cartItemId,
better return whole ShoppingCart in response, cart item on its own will be hardly of use to the Front-end

2024-09-02 09:30 UTC, okuzan commented on src/main/java/mate/academy/bookstore/dto/cartitem/CreateCartItemRequestDto.java
> +    private int quantity;
```suggestion
    @Positive
    private long bookId;
    @Positive
    private int quantity;

```

2024-09-02 09:30 UTC, okuzan commented on src/main/java/mate/academy/bookstore/dto/cartitem/UpdateCartItemRequestDto.java
> +    @Min(1)
same

2024-09-02 11:46 UTC, c-kalenyk commented
Interesting that without Transactional annotations any attempts to save, get or update ends up with LazyInitializationException. But exclusively on final mapping stage, even though i'm now fetching all required data by custom queries.

2024-09-02 14:16 UTC, Elena-Bruyako requested changes
see comments

2024-09-02 14:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/ShoppingCartController.java
> +        UserResponseDto user = userService.findByEmail(authentication.getName());
don't need to call db, get userId from Authentication

2024-09-02 14:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/ShoppingCartController.java
> +        UserResponseDto user = userService.findByEmail(authentication.getName());
same here

2024-09-02 14:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/dto/cartitem/CreateCartItemRequestDto.java
> +    @Positive
```suggestion
    @Positive
    @NotNull
```

2024-09-02 14:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/dto/shoppingcart/ShoppingCartDto.java
> +    private Long id;
```suggestion
    private Long id;
    Long userId;
```

2024-09-02 14:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Book.java
>      @ManyToMany(fetch = FetchType.LAZY)
```suggestion
    @ManyToMany
```

2024-09-02 14:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/CartItem.java
> +    @ManyToOne(fetch = FetchType.LAZY)
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-09-02 14:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/ShoppingCart.java
> +    @OneToMany(mappedBy = "shoppingCart", fetch = FetchType.LAZY)
```suggestion
    @OneToMany(mappedBy = "shoppingCart", cascade = CascadeType.ALL, orphanRemoval = true)
```

2024-09-02 14:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/User.java
>      @ManyToMany(fetch = FetchType.LAZY)
```suggestion
    @ManyToMany
```

2024-09-02 14:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/repository/book/BookRepository.java
> +    @Query("SELECT b FROM Book b LEFT JOIN FETCH b.categories WHERE b.id = :id")
```suggestion
    @EntityGraph(attributePaths = "categories")
```

more readable

2024-09-02 14:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/repository/book/BookRepository.java
> +    Optional<Book> findById(@Param("id") Long id);
```suggestion
    Optional<Book> findById(Long id);

```

2024-09-02 14:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/repository/shoppingcart/ShoppingCartRepository.java
> +    Optional<ShoppingCart> findById(@Param("id") Long id);
```suggestion
    @EntityGraph(attributePaths = {"cartItems", "cartItems.book"})
    Optional<ShoppingCart> findById(Long id);
```

2024-09-02 14:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/UserService.java
> +    UserResponseDto findByEmail(String email);
```suggestion
```

2024-09-02 14:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/impl/ShoppingCartServiceImpl.java
> +                        "Can't find shopping cart by id: " + shoppingCartId));
wrong message

2024-09-02 14:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/impl/ShoppingCartServiceImpl.java
> +                        "Can't find existing cart item by id: " + id));
```suggestion
        ShoppingCart cart = shoppingCartRepository.findByUserId(userId);
        CartItem cartItem = cartItemRepository.findByIdAndShoppingCartId(cartItemId, cart.getId()).....
```

2024-09-02 14:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/impl/ShoppingCartServiceImpl.java
> +        return shoppingCartMapper.toDto(shoppingCart);
```suggestion
        cartItemRepository.save(cartItem);
        return shoppingCartMapper.toDto(cart);
```

2024-09-02 14:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/impl/ShoppingCartServiceImpl.java
> +    public ShoppingCartDto getCartItems(Long shoppingCartId) {
method is named getCartItems but you return ShoppingCartDto, fix it

2024-09-02 14:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/impl/ShoppingCartServiceImpl.java
> +        ShoppingCart shoppingCart = shoppingCartRepository.findById(shoppingCartId)
It you try to get shop by user, you need to find shop cart by user id

2024-09-02 14:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/impl/UserServiceImpl.java
> +    public UserResponseDto findByEmail(String email) {
remove

2024-09-02 17:11 UTC, c-kalenyk commented
About shopping cart id and user id, i'm mapping it from user. There is only one cart per user anyway. So to simplify it a bit i can just use one id, no matter from which source of these two i will take it. If it's wrong - please, tell me

2024-09-03 07:52 UTC, Elena-Bruyako commented
> About shopping cart id and user id, i'm mapping it from user. There is only one cart per user anyway. So to simplify it a bit i can just use one id, no matter from which source of these two i will take it. If it's wrong - please, tell me

let's leave as it is

2024-09-03 07:55 UTC, Elena-Bruyako approved these changes
well done

2024-09-03 08:00 UTC, merged