added order entity
c-kalenyk/book-store pull request #15
Opened 2024-09-01 14:28 UTC by c-kalenyk

2024-09-02 12:25 UTC, Elena-Bruyako requested changes
see comments

2024-09-02 12:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/OrderController.java
> +    public Set<OrderDto> getOrdersHistory(Authentication authentication) {
```suggestion
    public Set<OrderDto> getOrdersHistory(Authentication authentication, @ParameterObject @PageableDefault Pageable pageable) {

```

2024-09-02 12:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/OrderController.java
> +        return orderService.getUserOrders(user.getId());
```suggestion
        User user = (User) authentication.getPrincipal();
        return orderService. getUserOrders(user.getId(), pageable);
```

2024-09-02 12:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/OrderController.java
> +        return orderService.create(user.getId(), requestDto);
```suggestion
        User user = (User) authentication.getPrincipal();
        return orderService. create(user.getId(), requestDto);
```

2024-09-02 12:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/OrderController.java
> +    OrderItemDto getOrderItem(@PathVariable Long orderId,
```suggestion
    public OrderItemDto getOrderItem(@PathVariable Long orderId,
```

2024-09-02 12:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/OrderController.java
> +    Set<OrderItemDto> getAllOrderItems(@PathVariable Long orderId) {
```suggestion
    public Set<OrderItemDto> getAllOrderItems(@PathVariable Long orderId, Authentication authentication) {
```

2024-09-02 12:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/OrderController.java
> +                              @PathVariable Long itemId) {
```suggestion
                              @PathVariable Long itemId, Authentication authentication) {
```
get user Id and provide it to service method
same for getAllOrderItems

2024-09-02 12:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Order.java
> +    @ManyToOne(fetch = FetchType.LAZY)
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-09-02 12:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Order.java
> +    private Status status;
```suggestion
    private Status status = Status.PENDING;
```

2024-09-02 12:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Order.java
> +    private LocalDateTime orderDate;
```suggestion
    private LocalDateTime orderDate = LocalDateTime.now();
```

2024-09-02 12:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Order.java
> +    @OneToMany(mappedBy = "order", fetch = FetchType.LAZY)
```suggestion
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, orphanRemoval = true)
```

2024-09-02 12:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/OrderItem.java
> +    @ManyToOne(fetch = FetchType.LAZY)
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-09-02 12:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/OrderItem.java
> +    @OneToOne(fetch = FetchType.LAZY)
```suggestion
    @OneToOne(fetch = FetchType.LAZY, optional = false)
```

2024-09-02 12:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/impl/OrderItemServiceImpl.java
> +    private final OrderItemRepository orderItemRepository;
replace all logic to order service

2024-09-02 12:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/impl/OrderServiceImpl.java
> +        }
```suggestion
        ShoppingCart cart = cartRepository.findByUserId(userId);
        if (cart.getCartItems().isEmpty()) {
            throw new OrderProcessingException("Cart is empty for user: " + userId);
        }
```

2024-09-02 12:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/impl/OrderServiceImpl.java
> +        return orderMapper.toDto(order);
```suggestion
        Order order = orderMapper.cartToOrder(cart, orderDto.shippingAddress());
        cart.clearCart();
        return orderMapper.toOrderDto(orderRepository.save(order));
```

where in OrderMapper
```
@Mapping(target = "id", ignore = true)
@Mapping(target = "total", source = "cart.cartItems", qualifiedByName = "total")
@Mapping(target = "orderItems", source = "cart.cartItems")
Order cartToOrder(ShoppingCart cart, String shippingAddress);
```
and 
```
@AfterMapping
default void updateOrder(@MappingTarget Order order) {
    order.getOrderItems().forEach(oi -> oi.setOrder(order));
}

@Named("total")
default BigDecimal getTotal(Set<CartItem> cartItems) {
    return cartItems.stream()
                .map(i -> i.getBook().getPrice().multiply(BigDecimal.valueOf(i.getQuantity())))
                .reduce(BigDecimal.ZERO, BigDecimal::add);
}
```

And in OrderItemMapper

```
@Mapping(target = "id", ignore = true)
@Mapping(target = "price", source = "book.price")
OrderItem cartItemToOrderItem(CartItem cartItem);
```

And in OrderMapper
```
@Mapping(target = "orderDate", dateFormat = "yyyy-MM-dd HH:mm")
@Mapping(target = "userId", source = "user.id")
OrderDto toOrderDto(Order order);
```

2024-09-03 16:39 UTC, MentorMateAcademy approved these changes

2024-09-03 17:55 UTC, merged