added docker
c-kalenyk/book-store pull request #16
Opened 2024-09-04 16:29 UTC by c-kalenyk

2024-09-05 11:14 UTC, okuzan requested changes
git rm --cached .env
add it to gitignore, don't expose it
create .env.template for env var names, without values

2024-09-05 11:14 UTC, okuzan commented on docker-compose.yml
> +      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
5005 is DEBUG PORT

2024-09-05 19:25 UTC, sarakhmen requested changes

2024-09-05 19:25 UTC, sarakhmen commented on .gitignore
> +git rm --cached .env
? :)

2024-09-05 19:25 UTC, sarakhmen commented on .env
don't expose this file as Oleh advised

2024-09-06 11:34 UTC, Elena-Bruyako approved these changes
well done

2024-09-06 11:36 UTC, merged