book controller implementation
c-kalenyk/book-store pull request #5
Opened 2024-08-22 18:11 UTC by c-kalenyk

2024-08-22 18:44 UTC, okuzan requested changes

2024-08-22 18:44 UTC, okuzan commented on src/main/java/mate/academy/bookstore/service/impl/BookServiceImpl.java
> +                .toList();
FYI you can declare mapping list to list in mapstruct inteface

2024-08-22 18:44 UTC, okuzan commented on src/main/java/mate/academy/bookstore/dto/CreateBookRequestDto.java
> +@Setter
it's ok to use Data on DTOs, but not on JPA entities

2024-08-22 18:44 UTC, okuzan commented on src/main/java/mate/academy/bookstore/controller/BookController.java
> +@RequestMapping("/api/books")
/api will be common for all controllers - extract it to application.properties 
server.servlet.context-path

2024-08-23 06:43 UTC, Elena-Bruyako approved these changes
Well done

2024-08-23 08:40 UTC, merged