criteria search implementation
c-kalenyk/book-store pull request #7
Opened 2024-08-24 12:18 UTC by c-kalenyk

2024-08-26 11:41 UTC, okuzan requested changes

2024-08-26 11:41 UTC, okuzan commented on src/main/java/mate/academy/bookstore/repository/book/BookSpecificationProviderManager.java
> +                .orElseThrow(() -> new RuntimeException(
change p to provider for clarity, replace exception with more precise and suitable NoSuchElementException

2024-08-26 11:41 UTC, okuzan commented on src/main/java/mate/academy/bookstore/service/impl/BookServiceImpl.java
> +                .toList();
use your toBookDtoList. You can rename this method to just toDto though

2024-08-28 09:50 UTC, MentorMateAcademy requested changes

2024-08-28 09:50 UTC, MentorMateAcademy commented on src/main/java/mate/academy/bookstore/repository/book/BookRepository.java
>  @Repository
```suggestion
```

2024-08-28 09:50 UTC, MentorMateAcademy commented on src/main/java/mate/academy/bookstore/repository/book/BookRepository.java
>  @Repository
not mandatory

2024-08-28 18:18 UTC, okuzan approved these changes

2024-08-28 19:22 UTC, merged